
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 192.168.1.135
  port: 5432
  username: postgres
  password: postgres

development:
  <<: *default
  database: heroes_api_development

test:
  <<: *default
  database: heroes_api_test

production:
  <<: *default
  database: heroes_api_production
  username: heroes_api
  password: <%= ENV["HEROES_API_DATABASE_PASSWORD"] %>
